apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# these will be executed in the order provided, including during retries for failures
# execution short circuits at the first failure.
- demo-ns.yaml
- gitops-system-ns.yaml
- gitops-connector-notifications.yaml
- test-ns.yaml
- test2-ns.yaml
- test3-ns.yaml
- test4-ns.yaml
- podinfo-repo.yaml
- podinfo-release.yaml
- generic-notifications.yaml
