apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ttlsh-helmrelease
  namespace: flux-system
spec:
  chart:
    spec:
      chart: testdemo
      version: "0.1.1"
      sourceRef:
        kind: HelmRepository
        name: ttlsh-helmrepository
        namespace: flux-system
  test:
    enable: false
    ignoreFailures: false
  interval: 10m
  targetNamespace: demo
  timeout: 1m
